#!/bin/sh

S3PATH=$1
if test $# -eq 2; then
    LOCALPATH=$2; shift; shift;
else
    LOCALPATH=./`basename ${S3PATH}`;
    shift;
fi
S3OPTS="${S3BASEOPTS:-$S3DEFAULTOPTS} $*";
if test ! -d ${LOCALPATH}; then
    if test -f ${LOCALPATH}; then
	echo "${LOCALPATH} already exists and is not a directory";
	exit;
    else
	mkdir ${LOCALPATH}; 
    fi
fi;
if test -f ${LOCALPATH}/.s3root; then
    echo "Overwriting ${LOCALPATH}/.s3root, saving into ${LOCALPATH}/.s3root.bak";
    mv ${LOCALPATH}/.s3root ${LOCALPATH}/.s3root.bak
fi; 
echo ${S3PATH} > ${LOCALPATH}/.s3root;
echo ${S3OPTS} > ~/.s3opts;
exec aws s3 cp --recursive ${AWS3OPTS} ${S3OPTS} ${S3PATH} ${LOCALPATH};

