#!/bin/sh

gets3root ( ) {
    if test $# -eq 0; then
	dir=`pwd`;
    elif test -z $1; then
	 dir=`pwd`;
    else
	dir=$1
    fi;
    dir = `realpath ${dir}`
    if test ! -d ${dir}; then
	dir=`dirname $dir`;
    elif;
    relpath=""
    while ( test ! -z "${dir}" && test ! -f .s3root ); do
	base = `basename ${dir}`;
	relpath = "${base}/${relpath}";
	dir = `dirname ${dir}`;
	done;
    if test -f ${dir}/.s3root; then
	echo "${dir}/";
	retval=0;
    else
	retval=1;
    fi;
}

if test $# -eq 0; then
    if gets3root `pwd`; then
	exit 0;
    else
	exit 1;
    fi;
else
    if gets3root $1; then
	exit 0;
    else
	exit 1;
    fi;
fi
    
