#!/bin/sh
LOCAL=`pwd`
S3ROOT=$1; shift
S3OPTS=$*
if test -f ${LOCAL}/.s3root;
   mv ${LOCAL}/.s3root ${LOCAL}/.s3root.bak;
   echo $1 > ${LOCAL}/.s3root
   if diff ${LOCAL}/.s3root ${LOCAL}/.s3root.bak; then
       echo "Existing .s3root ("`cat ${LOCAL}/.s3root.bak`") saved in ${LOCAL}/.s3root.bak";
   else
       echo "The current .s3root was already ${S3ROOT}";
   fi;
   if test $# -gt 1; then
       BASEOPTS=
       if test "$1" = "add" && test -f ${LOCAL}/.s3opts; then 
	   BASEOPTS=`cat ${LOCAL}/.s3opts`; shift; S3OPTS=$*;
       elif test "$1" = "defaults"; then
	   BASEOPTS=${S3SCRIPTOPTS}
       fi;
       echo ${BASEOPTS} ${S3OPTS} > ${LOCAL}/.s3opts;
   fi;
else
    echo "This directory (${LOCAL}) was not checked out of S3";
fi;
     

