#!/bin/sh

gets3src ( ) {
    scan=$1
    echo scan=${scan}
    scan=`realpath ${scan}`
    if test ! -d ${scan}; then
	scan= `dirname ${scan}`
    fi;
    relpath="";
    while ( test ! -z "${scan}" && test ! -f .s3root ); do
	base=`basename ${scan}`
	relpath="${scan}/${relpath}"
	scan=`dirname ${scan}`
    done;
    if test -f ${scan}/.s3root; then
	s3root=`cat ${scan}/.s3root`
	printf "%s\\n" "${s3root}/${relpath}/";
	retval=0
    else
	retval=1
    fi;
}
if test $# -eq 0; then
    gets3root `pwd`;
else
    gets3root $1;
fi
    
